default: &default
  account_sid:  ACbb3b3a4ad8cf20d7d1c8720c580afd0c
  auth_token:   c5983506e5ca100971a7642764b4c9d9
  from_tel:     '+16622987369'

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
